// components/DoubleButton.vue
<script setup>
defineProps({
  buttonTextLeft: {
    type: String,
    required: true,
  },
  leftLinkTo: {
    type: String,
    required: true,
  },
  buttonTextRight: {
    type: String,
    required: true,
  },
  rightLinkTo: {
    type: String,
    required: true,
  },
});
</script>

<template>
  <div class="flex flex-row w-fit border-2 border-[#e2dbaf] rounded-lg">
    <NuxtLink
      :to="leftLinkTo"
      target="_blank"
      class="w-fit px-4 py-2 hover:underline decoration-2 hover:underline-offset-4 text-md font-medium hover:bg-[#e2dbaf] rounded-l-lg hover:rounded-l-lg hover:text-[#1f2c1e] transition-all duration-200"
    >
      {{ buttonTextLeft }}
    </NuxtLink>
    <div class="border border-[#e2dbaf]"></div>
    <NuxtLink
      :to="rightLinkTo"
      class="w-fit px-4 py-2 hover:underline decoration-2 hover:underline-offset-4 text-md font-medium hover:bg-[#e2dbaf] rounded-r-lg hover:rounded-r-lg hover:text-[#1f2c1e] transition-all duration-200"
    >
      {{ buttonTextRight }}
    </NuxtLink>
  </div>
</template>

// src/app/components/Buttons/DoubleButton.jsx
import Link from "next/link";

export default function DoubleButton({
  buttonTextLeft,
  leftLinkTo,
  buttonTextRight,
  rightLinkTo,
}) {
  return (
    <div className="flex flex-row w-fit border-2 border-yellow-500 rounded-lg">
      <Link
        href={leftLinkTo}
        target="_blank"
        className="w-fit px-4 py-2 hover:underline decoration-2 hover:underline-offset-4 text-md font-medium hover:bg-yellow-500 rounded-l-lg hover:rounded-l-lg hover:text-darkgreen-500 transition-all duration-200"
      >
        {buttonTextLeft}
      </Link>
      <div className="border border-yellow-500"></div>
      <Link
        href={rightLinkTo}
        className="w-fit px-4 py-2 hover:underline decoration-2 hover:underline-offset-4 text-md font-medium hover:bg-yellow-500 rounded-r-lg hover:rounded-r-lg hover:text-darkgreen-500 transition-all duration-200"
      >
        {buttonTextRight}
      </Link>
    </div>
  );
}
