// components/TheFooter.vue
<template>
  <footer
    class="absolute bottom-0 w-full bg-[#15150F] p-4 md:p-6 text-center flex flex-col gap-6"
  >
    <nav class="flex flex-col lg:flex-row gap-6 items-center justify-between">
      <NuxtLink to="/">
        <img src="/img/vert-logo.svg" alt="VERT logo" class="h-[75px] w-auto" />
      </NuxtLink>
      <div class="flex flex-col lg:flex-row lg:space-x-10">
        <NuxtLink to="/brands" class="hover:text-[#3D67C3]">Brands</NuxtLink>
        <NuxtLink to="/team" class="hover:text-[#3D67C3]">Team</NuxtLink>
        <NuxtLink to="/documents" class="hover:text-[#3D67C3]"
          >Documents
        </NuxtLink>
        <NuxtLink to="/contact" class="hover:text-[#3D67C3]">Contact</NuxtLink>
      </div>
    </nav>
    <div class="flex flex-row justify-center">
      <h6 class="text-xs">© 2024 VERT Outdoors. All Rights Reserved.</h6>
    </div>
  </footer>
</template>

// src/app/components/TheFooter.jsx
import Link from "next/link";
import Image from "next/image";
import vertLogo from "../../../public/images/vert-logo.svg";

export default function TheFooter() {
  return (
    <footer className="absolute bottom-0 h-[300px] lg:h-[200px] w-full bg-darkbrown-500 p-4 md:p-6 text-center flex flex-col gap-6">
      <div className="flex flex-col h-full lg:flex-row gap-6 items-center justify-between">
        <Link href="/">
          <Image src={vertLogo} alt="VERT logo" height={75} />
        </Link>
        <div className="flex flex-col lg:flex-row lg:space-x-10">
          <Link href="/brands" className="hover:text-blue-hover">
            Brands
          </Link>
          <Link href="/team" className="hover:text-blue-hover">
            Team
          </Link>
          <Link href="/documents" className="hover:text-blue-hover">
            Documents
          </Link>
          <Link href="/contact" className="hover:text-blue-hover">
            Contact
          </Link>
        </div>
      </div>
      <div className="flex flex-row justify-center">
        <h6 className="text-xs">© 2024 VERT Outdoors. All Rights Reserved.</h6>
      </div>
    </footer>
  );
}
